from pathlib import Path

BASE_PATH = Path(__file__).parent.parent

SCREEN_WIDTH = 550
SCREEN_HEIGHT = 720

GROUND_HEIGHT = 100
GROUND_Y = SCREEN_HEIGHT - GROUND_HEIGHT
GROUND_SPEED = 1

PIPE_WIDTH = 50
PIPE_GAP_SIZE = 90
PIPE_SPAWN_TIME = 200

PLAYER_SIZE = 25
MAX_VELOCITY = 7.0
VELOCITY_RATE = 0.5

LOG_TIME = 60 * 3